#!/usr/bin/python
"""Wrapper for CSniffer, to be called as a standalone command (or from the GTK UI)."""

import sys

# Ugly but mandatory
sys.path.append('.')

import lib.globals as glob
import lib.ui.output_manager as om

# Debugging options.
glob.debug = False

# We create a console OM.
glob.om = om.OutputManager('console', debug=glob.debug)

import modules.gather.CSniffer as csniffer
sniffer = csniffer.CSniffer()
# This is so clowny...
setattr(sniffer, 'gom', glob.om)

sniffer.help_interactive()
sniffer.run()
